Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamodb}
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1