Resources:
  ## Specifying the S3 Bucket
  WebAppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: ${self:custom.bucketName}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  
  ## Bucket policy and making files available to CloudFront
  WebAppS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebAppS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::${self:custom.bucketName}/*


        